# Generated by Django 4.1.5 on 2023-01-19 16:40

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('texto', models.CharField(max_length=30, verbose_name='Texto')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 132, 'width': 132}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Midias',
            },
        ),
    ]
