# Generated by Django 4.1.5 on 2023-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='slide',
            field=models.CharField(choices=[('primeiro', 'Slide 1'), ('segundo', 'Slide 2')], max_length=8, verbose_name='Lado'),
        ),
    ]
