# Generated by Django 4.1.5 on 2023-01-19 18:54

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_design_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 345, 'width': 355}}, verbose_name='Imagem'),
        ),
    ]
