# Generated by Django 4.1.5 on 2023-01-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_design_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Medias'},
        ),
        migrations.AlterField(
            model_name='design',
            name='slide',
            field=models.CharField(choices=[('primeiro', 'Slide 1'), ('segundo', 'Slide 2')], max_length=8, verbose_name='Slide'),
        ),
    ]
